name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v6
      with:
        name: sticker
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build tests.nix
